spring:
  application:
    name: Festival Pulse
  datasource:
    url: jdbc:mysql://localhost:3306/festivalpulse?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    version: openapi_3_0
