spring:
  application:
    name: Festival Pulse
  datasource:
    url: jdbc:h2:mem:festivalpulse
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true

springdoc:
  api-docs:
    version: openapi_3_0
